import { Box, Container, CssBaseline, ThemeProvider } from "@mui/material";
import type { Metadata } from "next";
import { projectTheme } from "./theme";
import "../public/fonts.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "E Commerce Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={projectTheme}>
          <CssBaseline />
          <Header />
          <Box>
            <Container maxWidth="xl">{children}</Container>
          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
}
